// <auto-generated />
using System;

using Application.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using NetTopologySuite.Geometries;

using NodaTime;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Services.DatabaseInitializer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720204953_FixSpecialRelationshipWithVenuesAndMenus")]
    partial class FixSpecialRelationshipWithVenuesAndMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "address_standardizer");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "address_standardizer_data_us");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "plpgsql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_raster");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_sfcgal");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_tiger_geocoder");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_topology");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Domain.Entities.BusinessHoursEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<LocalTime?>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("close_time");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DayOfWeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_of_week_id");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<LocalTime?>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("open_time");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_business_hours");

                    b.HasIndex("DayOfWeekId")
                        .HasDatabaseName("ix_business_hours_day_of_week_id");

                    b.HasIndex("VenueId", "DayOfWeekId")
                        .IsUnique()
                        .HasDatabaseName("ix_business_hours_venue_day");

                    b.ToTable("business_hours", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.DayOfWeekEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWeekday")
                        .HasColumnType("boolean")
                        .HasColumnName("is_weekday");

                    b.Property<int>("IsoNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iso_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("short_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_days_of_week");

                    b.HasIndex("IsoNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_days_of_week_iso_number");

                    b.ToTable("days_of_week", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_special_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_special_categories_name");

                    b.ToTable("special_categories", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_data");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SpecialCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_category_id");

                    b.Property<Guid>("SpecialMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_menu_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_specials");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_specials_is_active");

                    b.HasIndex("SpecialCategoryId")
                        .HasDatabaseName("ix_specials_category_id");

                    b.HasIndex("SpecialMenuId")
                        .HasDatabaseName("ix_specials_special_menu_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_specials_venue_id");

                    b.ToTable("specials", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialMenuEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_special_menus");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_special_menus_venue_id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_special_menus_venue_name");

                    b.ToTable("special_menus", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialMenuScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<LocalTime>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<LocalDate?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SpecialMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_menu_id");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_special_menu_schedules");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_special_menu_schedules_is_active");

                    b.HasIndex("SpecialMenuId")
                        .HasDatabaseName("ix_special_menu_schedules_menu_id");

                    b.HasIndex("SpecialMenuId", "IsActive")
                        .HasDatabaseName("ix_special_menu_schedules_menu_active");

                    b.ToTable("special_menu_schedules", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Instant>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NameIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_identifier");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_address");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("NameIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_users_sub");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_venue_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_categories_name");

                    b.ToTable("venue_categories", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("PrimaryCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_category_id");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("SecondaryAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secondary_address");

                    b.Property<Guid?>("SecondaryCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_category_id");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street_address");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("time_zone_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_venues_is_active");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_venues_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_venues_name");

                    b.HasIndex("PrimaryCategoryId")
                        .HasDatabaseName("ix_venues_primary_category_id");

                    b.HasIndex("SecondaryCategoryId")
                        .HasDatabaseName("ix_venues_secondary_category_id");

                    b.HasIndex("TimeZoneId")
                        .HasDatabaseName("ix_venues_time_zone_id");

                    b.HasIndex("IsActive", "PrimaryCategoryId")
                        .HasDatabaseName("ix_venues_active_category");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueInvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VenueEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_entity_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<Guid?>("VenueRoleEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_role_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_venue_invitations");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_venue_invitations_accepted_by_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_venue_invitations_expires_at");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_venue_invitations_invited_by");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_venue_invitations_role_id");

                    b.HasIndex("VenueEntityId")
                        .HasDatabaseName("ix_venue_invitations_venue_entity_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_venue_invitations_venue_id");

                    b.HasIndex("VenueRoleEntityId")
                        .HasDatabaseName("ix_venue_invitations_venue_role_entity_id");

                    b.HasIndex("IsActive", "AcceptedAt")
                        .HasDatabaseName("ix_venue_invitations_active_accepted");

                    b.HasIndex("EmailAddress", "VenueId", "IsActive")
                        .HasDatabaseName("ix_venue_invitations_email_venue_active");

                    b.ToTable("venue_invitations", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_venue_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_roles_name");

                    b.ToTable("venue_roles", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueUserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_venue_user_roles");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_venue_user_roles_granted_by_user_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_venue_user_roles_is_active");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_venue_user_roles_role_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_venue_user_roles_venue_id");

                    b.HasIndex("UserId", "VenueId")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_user_roles_user_venue");

                    b.HasIndex("VenueId", "RoleId", "IsActive")
                        .HasDatabaseName("ix_venue_user_roles_venue_role_active");

                    b.ToTable("venue_user_roles", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.BusinessHoursEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.DayOfWeekEntity", "DayOfWeek")
                        .WithMany("BusinessHours")
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_business_hours_days_of_week_day_of_week_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany("BusinessHours")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_hours_venues_venue_id");

                    b.Navigation("DayOfWeek");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.SpecialCategoryEntity", "Category")
                        .WithMany("Specials")
                        .HasForeignKey("SpecialCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_specials_special_categories_special_category_id");

                    b.HasOne("Application.Domain.Entities.SpecialMenuEntity", "SpecialMenu")
                        .WithMany("Specials")
                        .HasForeignKey("SpecialMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specials_special_menus_special_menu_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specials_venues_venue_id");

                    b.Navigation("Category");

                    b.Navigation("SpecialMenu");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialMenuEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany("SpecialMenus")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_special_menus_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialMenuScheduleEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.SpecialMenuEntity", "SpecialMenu")
                        .WithMany("Schedules")
                        .HasForeignKey("SpecialMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_special_menu_schedules_special_menus_special_menu_id");

                    b.OwnsOne("Application.Domain.Entities.RecurrencePattern", "RecurrencePattern", b1 =>
                        {
                            b1.Property<Guid>("SpecialMenuScheduleEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DayOfMonth")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "day_of_month");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "day_of_week");

                            b1.Property<string>("Hours")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "hours");

                            b1.Property<string>("Minutes")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "minutes");

                            b1.Property<string>("Month")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "month");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "name");

                            b1.Property<string>("Seconds")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "seconds");

                            b1.Property<string>("Year")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "year");

                            b1.HasKey("SpecialMenuScheduleEntityId");

                            b1.ToTable("special_menu_schedules");

                            b1.ToJson("recurrence_pattern");

                            b1.WithOwner()
                                .HasForeignKey("SpecialMenuScheduleEntityId")
                                .HasConstraintName("fk_special_menu_schedules_special_menu_schedules_id");
                        });

                    b.Navigation("RecurrencePattern")
                        .IsRequired();

                    b.Navigation("SpecialMenu");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.VenueCategoryEntity", "PrimaryCategory")
                        .WithMany("PrimaryVenues")
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venues_venue_categories_primary_category_id");

                    b.HasOne("Application.Domain.Entities.VenueCategoryEntity", "SecondaryCategory")
                        .WithMany("SecondaryVenues")
                        .HasForeignKey("SecondaryCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_venues_venue_categories_secondary_category_id");

                    b.Navigation("PrimaryCategory");

                    b.Navigation("SecondaryCategory");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueInvitationEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.UserEntity", "AcceptedByUser")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_venue_invitations_users_accepted_by_user_id");

                    b.HasOne("Application.Domain.Entities.UserEntity", "InvitedByUser")
                        .WithMany("SentInvitations")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venue_invitations_users_invited_by_user_id");

                    b.HasOne("Application.Domain.Entities.VenueRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venue_invitations_venue_roles_role_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", null)
                        .WithMany("VenueInvitations")
                        .HasForeignKey("VenueEntityId")
                        .HasConstraintName("fk_venue_invitations_venues_venue_entity_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_invitations_venues_venue_id");

                    b.HasOne("Application.Domain.Entities.VenueRoleEntity", null)
                        .WithMany("VenueInvitations")
                        .HasForeignKey("VenueRoleEntityId")
                        .HasConstraintName("fk_venue_invitations_venue_roles_venue_role_entity_id");

                    b.Navigation("AcceptedByUser");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Role");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueUserRoleEntity", b =>
                {
                    b.HasOne("Application.Domain.Entities.UserEntity", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venue_user_roles_users_granted_by_user_id");

                    b.HasOne("Application.Domain.Entities.VenueRoleEntity", "Role")
                        .WithMany("VenueUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venue_user_roles_venue_roles_role_id");

                    b.HasOne("Application.Domain.Entities.UserEntity", "User")
                        .WithMany("VenueRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_user_roles_users_user_id");

                    b.HasOne("Application.Domain.Entities.VenueEntity", "Venue")
                        .WithMany("VenueUsers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_user_roles_venues_venue_id");

                    b.Navigation("GrantedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Application.Domain.Entities.DayOfWeekEntity", b =>
                {
                    b.Navigation("BusinessHours");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialCategoryEntity", b =>
                {
                    b.Navigation("Specials");
                });

            modelBuilder.Entity("Application.Domain.Entities.SpecialMenuEntity", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Specials");
                });

            modelBuilder.Entity("Application.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");

                    b.Navigation("VenueRoles");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueCategoryEntity", b =>
                {
                    b.Navigation("PrimaryVenues");

                    b.Navigation("SecondaryVenues");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueEntity", b =>
                {
                    b.Navigation("BusinessHours");

                    b.Navigation("SpecialMenus");

                    b.Navigation("VenueInvitations");

                    b.Navigation("VenueUsers");
                });

            modelBuilder.Entity("Application.Domain.Entities.VenueRoleEntity", b =>
                {
                    b.Navigation("VenueInvitations");

                    b.Navigation("VenueUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
